title: LucasWilsonGit
sass:
  load_paths:
    - assets/css
    - _sass
baseurl: ""#/home/lwilson/Development/jekyll/LucasWilsonGit.github.io/_site"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
    css_class: highlight
    enable_pygments: true
    use_span: true